src/config.rs

Some refactor is necessary. In this refactor, we should achieve:
* Ignore keysyms not followed by commands rather than returning an error
* Join keysyms ending with backslash the same way as commands.

refactor: config

---

src/daemon.rs

There is *a lot* of indentation in the main loop, which negatively affects readability. Some indentations are unnecessary and can be reduced with [guard clauses](https://maximegel.medium.com/what-are-guard-clauses-and-how-to-use-them-350c8f1b6fd2).
**Before:**
```rust
for state in &key_states {
for hotkey in &hotkeys {
if hotkey.modifiers.len() < state.iter().count() {
possible_hotkeys.push(hotkey.clone());
} else {
continue;
}
}
if !possible_hotkeys.is_empty() {
let mut state_modifiers: Vec<config::Modifier> = Vec::new();
let mut state_keysyms: Vec<evdev::Key> = Vec::new();
for key in state.iter() {
if let Some(modifier) = modifiers_map.get(&key) {
state_modifiers.push(*modifier);
} else {
state_keysyms.push(key);
}
}
log::debug!("state_modifiers: {:#?}", state_modifiers); …
```

refactor(daemon): reduce indent w/ guard clause

---

src/config.rs
src/daemon.rs

Add proper displaying of config errors to swhkd.
Config file:
```
1    p
2      notify-send "Hello world"
3  
4    super + W3%(*&)
5      firefox
```
Log:
```
[2022-02-13T04:23:44Z WARN  swhkd] Running swhkd as root!
[2022-02-13T04:23:44Z ERROR swhkd] Config Error: Unknown symbol at line 4.
```

feat: implement proper display config errors

---

Cargo.lock
Cargo.toml
src/config.rs

Support for multiple curly brace pairs.
Example:
```
super + {_, ctrl} + {_, shift} + {1-9}
dwmc {_, toggle}{view, tag}ex {0-8}
```

Config curly brace test

---

docs/swhkdrc
src/config.rs
src/tests.rs

Fixes #56
Add support for the following command mapping:
```
super + {\,, .}
```
Which is the same as:
```
super + {comma, .}
```
Because the brace syntax uses commas to separate tokens, `,` must be escaped with a backslash to be used as a keysym.

feat: add handling for comma maps inside braces

---

src/daemon.rs

I haven't found any documentation for evdev ioctls so I didn't know that they could fail.
Might fix #59

[fix] Don't error on update_auto_repeat failure

---

src/daemon.rs

swhkd ignores autorepeat events, so disabling autorepeat isn't needed.

Don't set the evdev autorepeat rate

---

src/daemon.rs
src/server.rs

The most visible change in this PR is that I changed several function / variable names to improve clarity. I've also added some blank lines in between some lines of code.
Examples:
- `check_config_xdg()` -> `fetch_xdg_config_path()`
- `check_keyboard()` -> `check_device_is_keyboard()`
- `paused` -> `execution_is_paused`
`permission_check` is now `check_user_permissions`, and it now returns a `Result<T, E>` as opposed to exiting the program within the function. I made it so that **all** calls to `exit()` are in `fn main()` so that contributors can follow the logic of the program better.
The `send_command` function was defined in `main`. I moved it outside as function definitions shouldn't go in `main`.
There was also improper indentation, which resulted in some unclean closing braces in …

refactor: improve daemon / server code

---

src/daemon.rs

Some log statements don't appear that clear to the end user.
For example, when swhkd receives a misc. signal:
```rust
log::warn!("Got signal: {:#?}", signal);
exit(1);
``` 
It only says that it received a signal, but nothing about exiting the program. This can be confusing, so I added a message to say that swhkd is going to exit:
```rust
log::warn!("Received signal: {:#?}", signal);
log::warn!("Exiting...");
exit(1);
```
When swhks receives a message from swhkd, all information about the message is condensed into one line:
```rust
log::debug!("Socket: {:?} Address: {:?} Response: {}", socket, address, response);
```
Splitting the three fields into three lines improves the clarity of the log:
```rust
log::debug!("MESSAGE:");
log::debug!("Socket: {:?}", socket);
log::debug!("Address: {:?}", …
```

feat: improve logs in daemon/server

---

src/server.rs

My solution is just to have a function that checks if there is a xdg runtime dir variable and then use if it is exists. If not fallback to /run/user/{uid}.

Support for the xdg runtime dir variable has already been added in the daemon but not the server.

---

src/daemon.rs
src/perms.rs

Descriptions of the two CVEs [(source)](https://www.openwall.com/lists/oss-security/2022/04/14/1):
```
2.b) The `-c` Daemon Command Line Parameter Allows for Arbitrary File Existence Tests (CVE-2022-27814)
------------------------------------------------------------------------------------------------------
Example exploitation:
$ pkexec /usr/bin/swhkd -d -c /root/.somefile
[2022-03-22T12:32:25Z ERROR swhkd] "/root/.somefile" doesn't exist
$ pkexec /usr/bin/swhkd -d -c /root/.bash_history
[...] (daemon starts "normal" operation)
2.c) The `-c` Daemon Command Line Parameter Allows to Parse Arbitrary Files (CVE-2022-27819)
--------------------------------------------------------------------------------------------
The file passed to `swhkd` via `-c` will be completely read in by
`swhkd`. Any …
```

fix: patch CVE-2022-27814 and CVE-2022-27819

---

README.md

Noticed a punctuation error in the readme, double comma is only used for interrupters or parenthetical elements, which meaning is not in this case.
(sorry if I did anything wrong with this pr, is my first time contributing to a project)

fixing a punctuation error in the readme

---

swhkd.5.scd

* swhkd.5.scd: rename sniff to swhkd

[update] fix typo

---

docs/swhks.1.scd
swhks/src/main.rs

If `XDG_DATA_HOME` is not set, `swhks` defaults to `~/.local/share/swhks/swhks-{time}.log` for its log files. Unfortunately, `~` is not translated dynamically to the `HOME` user directory path at runtime.
This PR fixes this issue by replacing `~` with a reference to the `HOME` environment variable. If this variable is not set too, the application exits with an error message, as there does not seem to be a way to recover properly in this case.
Closes #157.

[fix] default `swhks` logpath now references `HOME` environment variable instead of `~`

---

swhks/src/main.rs

There was a `/` left at the end of the log file path in swhks, which causes it to exit upon running a command.

[fix] log path being treated as directory

---

swhkd/src/daemon.rs

swhkd now continues through all "potential" hotkeys so that release hotkeys are still executed, rather than shadowed by a keypress bind.
Fixes #159.

[fix] release key event shadowed by press event

---

swhkd/src/daemon.rs

As a fix for CVE-2022-27814, root privileges are dropped to the calling user when (re)loading the config file. Privileges were sometimes dropped but never raised again, which caused crashes when sending SIGHUP to swhkd multiple times in a row.
This now always raises privileges after successfully reading the config file.
Fixes #155.

[fix] raise swhkd privileges right after reading config

---

swhkd/src/daemon.rs
swhkd/src/uinput.rs

Ignored events (i.e. events other than key presses for now) are re-emitted to the uinput devices. This allows grabbing mouses and other pointer devices while still allowing the cursors to work.
In some cases, events are not re-emitted at all when the uinput device handles keys, relative axes and switches. By sending switch events to a separate uinput device just for switches and another one for keys and relative axes, we can re-emit keys, pointer events, and switches events properly.

Re-emit ignored events from grabbed devices to uinput devices

---

Cargo.lock
docs/swhkd.5.scd
swhkd/src/config.rs
swhkd/src/daemon.rs

Mode options:
```rust
pub struct Mode {
pub name: String,
pub hotkeys: Vec<Hotkey>,
pub unbinds: Vec<KeyBinding>,
pub options: ModeOptions,
}
pub struct ModeOptions {
pub swallow: bool,
pub onceoff: bool,
}
```
Mode options are declared after the mode name.
Syntax:
`mode modename option1 option2`
Currently, two options are implemented: `swallow` and `onceoff`
`swallow`: Don't emit any event through uinput.
`onceoff`: Automatically escape a mode when a keybinding defined in it is evoked. @BlueDrink9 This may solve #164.
We can add more options by adding members to the `ModeOptions` struct.

[feat] implment mode options

---

swhkd/src/uinput.rs

This fixes a bug introduced in af0115e and closes #174 
After creating a uinput device with switches support, all radio devices were blocked. This was due to rfkill reacting to the uinput creation.
We disable rfkill-input (the module reacting to new device creation) to avoid blocking all radio devices. When a new device (virtual or physical) with the SW_RFKILL_ALL switch capability bit set appears, rfkill reacts immediately depending on the value bit. This value bit defaults to unset, which causes rfkill to use its default eop mode (emergency power off). The uinput API does not give any way to set the corresponding value bit before creating the device, and we have no way to avoid rfkill acting upon the device creation or to change its default mode. Thus, we disable rfkill-input …

Stop rfkill from blocking all radio devices

---

.editorconfig

This matches what is expected by rustfmt and what is explained in the CONTRIBUTING.md guidelines.

Use space for rust files in editorconfig

---

swhkd/src/config.rs

Had an issue where a keycombo like `~control + left` was registering as just the left key without modifiers. This makes sure to strip any tildes or at signs before matching the modifier to the table.

Strip ~ and @ from modifiers before matching them

---

Cargo.lock
swhkd/Cargo.toml
swhks/Cargo.toml

This better reflects the current development version and should make it less confusing for users, as mentioned in #178.
This also includes a dependency version update.

Update version in Cargo.toml and Cargo.lock to 1.3.0-dev

---

INSTALL.md
Makefile
contrib/PKGBUILD

This PR depends on #184 which must be merged before this one.
This adds a `DESTDIR` variable to the `Makefile` which acts as a prefix for all directories in the `install` make target. This will make it much easier to package swhkd, as now building and installing boils down to: `make && make DESTDIR="packaging_subdir" install`. The default is still to install to the root.
This PR also updates `contrib/PKGBUILD` to make use of this updated `install` make target.

Add DESTDIR variable to Makefile

---

CHANGELOG.md

This changelog is based on [Keep a Changelog](https://keepachangelog.com/en/1.0.0/) as discussed in #181.
For now, it only contains unreleased changes. These changes are tracked based on where the future 1.2.2 version will be. I decided to include build system changes in there, just because it might be important/useful for package maintainers.
Contributors are not listed in this version of the changelog directly to keep it lean. This is debatable, but I think contributors should be listed (and thanked!) in the GitHub releases instead. Feel free to open an issue to discuss this further if needed.
I am open to suggestion for changes to the current text, the format, or anything else.

Add first version of changelog file

---

CHANGELOG.md
Makefile

This is a simple typo fix to man5 docs being installed in the man1 location.

Install man docs to correct location

---

docs/swhkd-keys.5.scd
swhkd/src/config.rs
swhkd/src/daemon.rs
swhkd/src/tests.rs

Changes the behavior of the right alt key. Now the right alt key will be it's own independent modifier key. 
The right alt key is usually called the "alt graph" or "alt gr" keys on non-us English keyboards. 
The alt gr key usually allows for typing foreign symbols, accented letters, äßöü, etc. However since swhkd treats the right alt the same as the left alt, there was no way to type these characters.
The changes made allow for users to keep using the left alt key to work as normal, but give the choice to users to utilise another "layer" of characters, or another "layer" of hotkeys. Hence, it does not remove any functionality, and not break any configuration files.
https://en.wikipedia.org/w/index.php?title=QWERTY&lang=en#United_States
https://en.wikipedia.org/wiki/Alt_key?lang=en …

Implement altgr modifier

---

contrib/init/systemd/README.md

$XDG_CONFIG_DIR does not seem to be part of the XDG Base Directory Specification, systemd/user is in $XDG_CONFIG_DIRS
Changed to $XDG_CONFIG_DIRS

docs(readme): fix typo in systemd readme

---

swhks/src/main.rs

Overriding the RUST_LOG variable means it propagates to rust programs spawned by swhks, directly and indirectly.
implementation inspired by the example in the [env_logger](https://docs.rs/env_logger/latest/env_logger/#specifying-defaults-for-environment-variables) docs.

[fix] don't override global RUST_LOG variable

---

swhkd/src/config.rs
swhkd/src/tests.rs

- Removed `load_file_contents` which is a manual implementation of `fs::read_to_string`.
- Replaced respective occurrences in `Config::new` and tests.

refactor: remove manual implementation of `fs::read_to_string`

---

INSTALL.md

This is my first time comping this repo (with Rust official docker image). I had to add `libudev-dev` to compile. Adding that to the doc.

Add libudev compile requirement to INSTALL.md

---

.gitignore
swhkd/src/daemon.rs
swhkd/src/uinput.rs

- This helps remove unnecessary mut's
- Using static slice prevents the need to create Vec which is discarded anyway
- Prevent *rc patten from matching src/ directories
- Propogate errors in uinput::create_uinput_device*() instead of unwrap

[refactor] replace manual insertions with collects

---

.gitignore
swhks/src/environ.rs
swhks/src/main.rs

This PR implements the following changes, these changes have been limited to `swhks` for feedback and review, but they can be extended into the actual `swhkd` as well.
The env struct is used to centrally handle all the environment related queries and initializations. It is opened as a thread safe `OnceLock` variable and hence is ideal for servers
Error handling related to env is now centrally handled in the Env struct itself using typecasted enumerations
Paths are now handled with `pathbufs` instead of format strings
This PR lays the ground work in centralizing the Environment variable queries that would help abstract away all the individual queries. This could especially be helpful when we modify the privilege model since we would now need to do changes in only a few places
Additionally, …

[refactor] environment variable initialization

---

swhkd/src/config.rs

- Replaced the body of the `strip_at` function to call `trim_start_matches` on a string to strip the `@` and `~` chars.
- Removed obsolete `strip_tilde` function.
- Cached the results of `strip_at` applied on `token_new` into `tokens_no_at`. The values are used in the subsequent for loop and for building the modifiers vector.
Tests are passing.

refactor: use `trim_start_matches` to remove tilde and at symbols

---

swhkd/src/daemon.rs
swhkd/src/environ.rs
swhks/src/environ.rs

This change introduces similar changes as #243 for `swhkd`.
The following were the changes made:
- Added a new `environ.rs` which is central to the environment management system
- Refactored `env::var` uses across the `daemon.rs`
- Removed unsafe env uses

[refactor] environment for swhkd

---

Makefile

Currently, if an `swhkdrc` file exists at the time of installation, `make install` will overwrite it. This also happens when updating the `swhkd-git` package on Arch, for example.
It would be preferable to only create the blank file if a configuration does not exist already.

[fix] don't overwrite configuration file

---

Cargo.lock
swhkd/Cargo.toml
swhkd/src/daemon.rs
swhks/Cargo.toml
swhks/src/main.rs

This patch removes the usage of clap::Command and arg macros, and bumps
the library version to use the new derive API which is the recommended
method upstream.

[feat] use clap Derive API to accept command line arguments

---

swhkd/src/daemon.rs

The `send_command` macro in SWHKD's `daemon.rs` component accepts expressions with the same datatype in all invocations. Moving it into a function helps language servers like Rust Analyzer make inferences easier because the expressions become concrete types.

refactor: move `send_command` macro into a function

---

swhkd/Cargo.toml

Fixes https://github.com/waycrate/sweet/issues/1
- Bumped dependency sweet to 0.4.0
- Reorder conflicting keys in descending order to avoid greedy parsing of shorter variants

deps: bump sweet

---

Cargo.lock

Build was failing on alpine for loongarch64.
https://build.alpinelinux.org/buildlogs/build-edge-loongarch64/testing/swhkd/swhkd-1.2.1-r0.log
libc 0.2.159 adds support for loongarch64

upgrade libc to 0.2.159

---

swhkd/src/config.rs
swhkd/src/daemon.rs

The new logging system seems to discard the source of a grammar error.
Fixed that by checking and displaying the error if it exists.

fix: display error source for grammar errors if they exist

---

swhkd/src/daemon.rs

There was hash prepended to the actual environment variables string received from swhks
since [UnixStream::read_to_string](https://doc.rust-lang.org/std/os/unix/net/struct.UnixStream.html#method.read_to_string-1) method is append to buffer instead of overwriting, the result of previous read still persists in the buffer resulting in invalid variable.
This happens when the previous hash do not match and hence request for latest variables is made to swhks and read into the same buffer hash was read in (which appends).
clear the buffer before reading next string.
Fixes  #279

[Fix] Clear the buffer before reading again, fixes #279

---

swhkd/src/daemon.rs
swhkd/src/environ.rs

Since swhkd runs in elevated perms, at no time it should capture the environment variables. 
Currently the call to `environ::Env::construct(None)` is made to initialize env, which captures the environment of swhkd although this is always overwritten it could lead to security issues so its better to initialize it empty

Enhancement: swhkd binary should never read environment

---

swhkd/Cargo.toml

fix spelling mistake in Cargo.toml:
changed `TYY` to `TTY`

[fix] spelling error in Cargo.toml

---

Cargo.lock

should fix swhkd-git aur package failing to build, issue #281

chore: updates cargo.lock

---

swhkd/src/daemon.rs

Better specify error context when failing to create uinput devices.
potentially related #282

Enhancement: specify error context

---

swhkd/src/config.rs
swhkd/src/environ.rs

This commit makes `environ.rs` more optimized by removing redundant
`.to_string()` allocations by using **borrow::Cow (copy-on-write)**.
1. Used filter_map for single pass instead of manual iteration through
env.lines()
2. Replace most .to_string() with Cow to remove unnecessary string
allocations
3. In `construct` function, used `env::vars.collect()` to get all values
in one pass instead of allocation new string, also now returns `env::vars`
by default instead of an empty `HashMap<String, String>`.
4. Add some comments for more readability.
This PR was tested with:
```bash
make check
make test
```
I did not create any new functions so **NO** tests were added or modified.

fix: Optimize environ.rs to avoid redundant string allocations

---

swhkd/src/daemon.rs
swhkd/src/uinput.rs
swhks/src/ipc.rs

**Summary of changes:**
1. Calculate hash function now borrows the string instead of taking
ownership
2. Used match to check for buffer byte instead of if statement
3. Added more debug logging and error handling
In `swhkd/src/daemon.rs`:
1. Replaced `map_for` with `is_some_and` as it is more efficient in this
case (simple bool ops)
This PR was tested with:
```bash
make test
```
**Note:**
I tried to modify `uinput.rs` to fix the rfkill issue but the logic did not really work so I had to fallback to the latest commit on swhkd (kindly ignore it)
I did not create any new tests as I just modified functional logic only.

fix: refined swhks ipc.rs for hash calculation and finding buffer byte

---

Cargo.lock
INSTALL.md
Makefile
contrib/PKGBUILD
swhkd/Cargo.toml
swhkd/src/uinput.rs

Combines this commit [commit](https://github.com/waycrate/swhkd/commit/9701b3f787d2e546cb4837d330cd7037e78f4665l) and #254 .
works on arch linux with mediatek MT7921 wifi module. 
wifi stops resting as expected with --no-default-features flags, although i am not able to test with a rfkill switch yet

Fix: Added rfkill support as a feature flag
